/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.alex.dahouetecf.GUI.model;

import com.alex.dahouetecf.GUI.dao.ClasseDAO;
import com.alex.dahouetecf.GUI.dao.ProprietaireDAO;
import com.alex.dahouetecf.GUI.dao.SerieDAO;
import com.alex.dahouetecf.GUI.dao.VoilierDAO;
import com.alex.dahouetecf.GUI.dao.JDBC;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;
//import net.sf.jasperreports.engine.JRException;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.engine.util.JRLoader;
//import net.sf.jasperreports.swing.JRViewer;
//import sun.applet.Main;

/**
 *
 * @author alex
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
    //VoilierJTable vjt;
    
    public MainWindow() {
        
        initComponents();
        
          int serie = ((Serie) comboboxSerie.getSelectedItem()).getId_serie();
        System.out.println(ClasseDAO.findBy(serie).toArray().length + " " + serie);
        comboboxClasse.setModel(new javax.swing.DefaultComboBoxModel(ClasseDAO.findBy(serie).toArray()));

        initListProprio();

        comboboxClasse.setVisible(false);
        labelClasse.setVisible(false);
        comboboxProprietaire.setVisible(false);
        labelProprietaire.setVisible(false);
        btnAjoutVoilier1.setEnabled(false);
    }
     public void initListProprio() {
        List<Proprietaire> proprietaires = ProprietaireDAO.findAllProprietaire();
        for (Proprietaire p : proprietaires) {
            comboboxProprietaire.addItem(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        jMenu1 = new javax.swing.JMenu();
        jPanelVoilier = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelSerie = new javax.swing.JLabel();
        labelClasse = new javax.swing.JLabel();
        labelProprietaire = new javax.swing.JLabel();
        nomVoilier = new javax.swing.JTextField();
        numVoilier = new javax.swing.JTextField();
        comboboxSerie = new javax.swing.JComboBox<>();
        comboboxClasse = new javax.swing.JComboBox();
        comboboxProprietaire = new javax.swing.JComboBox<>();
        messageVoilier = new java.awt.Label();
        btnAjoutVoilier1 = new javax.swing.JButton();
        jPanelProprietaire = new javax.swing.JPanel();
        jPanelIdentProprio = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        prenomProprietaire = new javax.swing.JTextField();
        nomProprietaire = new javax.swing.JTextField();
        mailProprietaire = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanelLicence = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        numDeLicence = new javax.swing.JTextField();
        anneeDeLicence = new javax.swing.JTextField();
        nomDuClub = new javax.swing.JTextField();
        btnAjoutProprietaire = new javax.swing.JButton();
        messageProprietaire = new java.awt.Label();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelVoilier.setBorder(javax.swing.BorderFactory.createTitledBorder("Voilier"));
        jPanelVoilier.setToolTipText("");

        jButton1.setText("pdf");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom");

        jLabel2.setText("N° de voile");

        labelSerie.setText("Série");

        labelClasse.setText("Classe");

        labelProprietaire.setText("Propriétaire");

        numVoilier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numVoilierActionPerformed(evt);
            }
        });

        comboboxSerie.setToolTipText("Choix série");
        List<Serie> series = SerieDAO.findAllSerie();         for (Serie s : series) {             comboboxSerie.addItem(s);         }
        comboboxSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxSerieActionPerformed(evt);
            }
        });

        comboboxClasse.setToolTipText("Choix classe");
        comboboxClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxClasseActionPerformed(evt);
            }
        });

        comboboxProprietaire.setToolTipText("Choix propriétaire");

        messageVoilier.setText("label2");

        btnAjoutVoilier1.setText("Envoyer");
        btnAjoutVoilier1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjoutVoilier1MouseClicked(evt);
            }
        });
        btnAjoutVoilier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutVoilier1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVoilierLayout = new javax.swing.GroupLayout(jPanelVoilier);
        jPanelVoilier.setLayout(jPanelVoilierLayout);
        jPanelVoilierLayout.setHorizontalGroup(
            jPanelVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVoilierLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanelVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelVoilierLayout.createSequentialGroup()
                        .addGroup(jPanelVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(labelClasse)
                            .addComponent(labelProprietaire)
                            .addComponent(labelSerie))
                        .addGap(68, 68, 68)
                        .addGroup(jPanelVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomVoilier)
                            .addComponent(numVoilier)
                            .addComponent(comboboxSerie, 0, 198, Short.MAX_VALUE)
                            .addComponent(comboboxClasse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboboxProprietaire, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelVoilierLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAjoutVoilier1)))
                .addGap(75, 75, 75)
                .addComponent(messageVoilier, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVoilierLayout.setVerticalGroup(
            jPanelVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVoilierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomVoilier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numVoilier)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVoilierLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboboxSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSerie)))
                    .addGroup(jPanelVoilierLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(messageVoilier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClasse)
                    .addComponent(comboboxClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProprietaire)
                    .addComponent(comboboxProprietaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnAjoutVoilier1))
                .addGap(156, 156, 156))
        );

        jPanelProprietaire.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter propriétaire"));

        jPanelIdentProprio.setBorder(javax.swing.BorderFactory.createTitledBorder("Identité propriétaire"));

        jLabel7.setText("Nom");

        jLabel8.setText("Mail");

        prenomProprietaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomProprietaireActionPerformed(evt);
            }
        });

        jLabel12.setText("Prénom");

        javax.swing.GroupLayout jPanelIdentProprioLayout = new javax.swing.GroupLayout(jPanelIdentProprio);
        jPanelIdentProprio.setLayout(jPanelIdentProprioLayout);
        jPanelIdentProprioLayout.setHorizontalGroup(
            jPanelIdentProprioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdentProprioLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanelIdentProprioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addGap(42, 42, 42)
                .addGroup(jPanelIdentProprioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prenomProprietaire, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(nomProprietaire)
                    .addComponent(mailProprietaire))
                .addContainerGap())
        );
        jPanelIdentProprioLayout.setVerticalGroup(
            jPanelIdentProprioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIdentProprioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelIdentProprioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(prenomProprietaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(24, 24, 24)
                .addGroup(jPanelIdentProprioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nomProprietaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelIdentProprioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(mailProprietaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLicence.setBorder(javax.swing.BorderFactory.createTitledBorder("Licence"));

        jLabel9.setText("N°");

        jLabel10.setText("Année");

        jLabel11.setText("Club");

        javax.swing.GroupLayout jPanelLicenceLayout = new javax.swing.GroupLayout(jPanelLicence);
        jPanelLicence.setLayout(jPanelLicenceLayout);
        jPanelLicenceLayout.setHorizontalGroup(
            jPanelLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLicenceLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanelLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(67, 67, 67)
                .addGroup(jPanelLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numDeLicence, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(anneeDeLicence)
                    .addComponent(nomDuClub))
                .addContainerGap())
        );
        jPanelLicenceLayout.setVerticalGroup(
            jPanelLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLicenceLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLicenceLayout.createSequentialGroup()
                        .addGroup(jPanelLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(numDeLicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10))
                    .addComponent(anneeDeLicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelLicenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nomDuClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAjoutProprietaire.setText("Envoyer");
        btnAjoutProprietaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjoutProprietaireMouseClicked(evt);
            }
        });
        btnAjoutProprietaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutProprietaireActionPerformed(evt);
            }
        });

        messageProprietaire.setText("label1");

        javax.swing.GroupLayout jPanelProprietaireLayout = new javax.swing.GroupLayout(jPanelProprietaire);
        jPanelProprietaire.setLayout(jPanelProprietaireLayout);
        jPanelProprietaireLayout.setHorizontalGroup(
            jPanelProprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProprietaireLayout.createSequentialGroup()
                .addGroup(jPanelProprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelProprietaireLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(messageProprietaire, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAjoutProprietaire))
                    .addGroup(jPanelProprietaireLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanelIdentProprio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jPanelLicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanelProprietaireLayout.setVerticalGroup(
            jPanelProprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProprietaireLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelProprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelLicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelIdentProprio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProprietaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageProprietaire, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProprietaireLayout.createSequentialGroup()
                        .addComponent(btnAjoutProprietaire)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelVoilier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelProprietaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jPanelVoilier, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelProprietaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prenomProprietaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomProprietaireActionPerformed
   
    }//GEN-LAST:event_prenomProprietaireActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       /*    try {
        JasperReport report = (JasperReport) JRLoader.loadObject(MainWindow.class.getResource("../reports/Cherry.jasper"));
        report.setProperty("net.sf.jasperreports.awt.ignore.missing.font", "false");
       report.setProperty("net.sf.jasperreports.default.font.name=SansSerif", "true");
       HashMap<String, Object> params = new HashMap<>();

      JasperPrint jPrint = JasperFillManager.fillReport(report, params, JDBC.getConnection());

        JFrame pdfFrame = new JFrame("Rapport");
        pdfFrame.getContentPane().add(new JRViewer(jPrint));
        pdfFrame.pack();
        pdfFrame.setSize(this.getSize());
        pdfFrame.setVisible(true);

    } catch (JRException ex) {
        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
    }
        */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboboxClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxClasseActionPerformed
        comboboxProprietaire.setVisible(true);
        labelProprietaire.setVisible(true);
    }//GEN-LAST:event_comboboxClasseActionPerformed

    private void comboboxSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxSerieActionPerformed
        int serie = ((Serie) comboboxSerie.getSelectedItem()).getId_serie();
        comboboxClasse.setModel(new javax.swing.DefaultComboBoxModel(ClasseDAO.findBy(serie).toArray()));

        comboboxClasse.setVisible(true);
        labelClasse.setVisible(true);
    }//GEN-LAST:event_comboboxSerieActionPerformed

    private void numVoilierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numVoilierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numVoilierActionPerformed

    private void btnAjoutVoilier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutVoilier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjoutVoilier1ActionPerformed

    private void btnAjoutVoilier1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjoutVoilier1MouseClicked
       String nom_Voilier = nomVoilier.getText();
        String num_Voilier = numVoilier.getText();
        Object listeClasse = comboboxClasse.getSelectedItem();
        Object listeProprio = comboboxProprietaire.getSelectedItem();
 
        Classe classe = (Classe) listeClasse;
        Proprietaire proprietaire = (Proprietaire) listeProprio;

        if (nom_Voilier.isEmpty() || num_Voilier.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tous les champs n'ont pas été remplis", "ERREUR", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                int strTxtNumVoile = Integer.parseInt(num_Voilier);
                Voilier voi = new Voilier(nom_Voilier, strTxtNumVoile, proprietaire, classe);
                VoilierDAO.insert(voi);
                //vjt.addVoilier(voi);
                nomVoilier.setText(null);
                numVoilier.setText(null);
                comboboxClasse.setVisible(false);
                labelClasse.setVisible(false);
                comboboxProprietaire.setVisible(false);
                labelProprietaire.setVisible(false);
               // btnAjoutVoilier1.setVisible(false);
                messageVoilier.setText("Le voilier a bien été ajouté.");
                messageVoilier.setForeground(Color.blue);
            } catch (Exception e) {
                messageVoilier.setText("ERREUR");
                messageVoilier.setForeground(Color.red);
            }
        }
    }//GEN-LAST:event_btnAjoutVoilier1MouseClicked

    private void btnAjoutProprietaireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjoutProprietaireMouseClicked
      String nomPersonne = nomProprietaire.getText();
        String prenomPersonne = prenomProprietaire.getText();
        String emailPersonne = mailProprietaire.getText();
        String numLicence = numDeLicence.getText();
        String anneeLicence = anneeDeLicence.getText();
        String nomClub = nomDuClub.getText();

        if (nomPersonne.isEmpty() || prenomPersonne.isEmpty() || emailPersonne.isEmpty() || numLicence.isEmpty() || anneeLicence.isEmpty() || nomClub.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs", "ERREUR", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                int strtxtAddProNumLicence = Integer.parseInt(numLicence);
                int strtxtAddProAnneeLicence = Integer.parseInt(anneeLicence);
                Proprietaire pro = new Proprietaire(nomPersonne, prenomPersonne, emailPersonne, strtxtAddProNumLicence, strtxtAddProAnneeLicence, nomClub);
                ProprietaireDAO.insertProprietaire(pro);
                messageProprietaire.setText("Le propriétaire a été enregistré.");
                messageProprietaire.setForeground(Color.blue);
                comboboxProprietaire.removeAllItems();
                initListProprio();
                nomProprietaire.setText(null);
                prenomProprietaire.setText(null);
                mailProprietaire.setText(null);
                numDeLicence.setText(null);
                anneeDeLicence.setText(null);
                nomDuClub.setText(null);

            } catch (Exception e) {
                messageProprietaire.setText("ERREUR");
                messageProprietaire.setForeground(Color.red);
            }
        }  
    }//GEN-LAST:event_btnAjoutProprietaireMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
     
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnAjoutProprietaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutProprietaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjoutProprietaireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anneeDeLicence;
    private javax.swing.JButton btnAjoutProprietaire;
    private javax.swing.JButton btnAjoutVoilier1;
    private javax.swing.JComboBox<Classe> comboboxClasse;
    private javax.swing.JComboBox<Proprietaire> comboboxProprietaire;
    private javax.swing.JComboBox<Serie> comboboxSerie;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanelIdentProprio;
    private javax.swing.JPanel jPanelLicence;
    private javax.swing.JPanel jPanelProprietaire;
    private javax.swing.JPanel jPanelVoilier;
    private javax.swing.JLabel labelClasse;
    private javax.swing.JLabel labelProprietaire;
    private javax.swing.JLabel labelSerie;
    private javax.swing.JTextField mailProprietaire;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    private java.awt.Label messageProprietaire;
    private java.awt.Label messageVoilier;
    private javax.swing.JTextField nomDuClub;
    private javax.swing.JTextField nomProprietaire;
    private javax.swing.JTextField nomVoilier;
    private javax.swing.JTextField numDeLicence;
    private javax.swing.JTextField numVoilier;
    private javax.swing.JTextField prenomProprietaire;
    // End of variables declaration//GEN-END:variables
}
